### ISSUE TITLE
Plugin not working under windows with wsl

### ISSUE THREAD

**Issue by jeromemartin** [timo-reymann/idea-ansible-vault-integration#1]
I have tried to configure ansible-vault with the command:

![image](https://user-images.githubusercontent.com/25756297/118824482-2ccd1e00-b8ba-11eb-9fae-a9f63c7a2b79.png)

Then i get the following error when trying to encrypt:

`Error: Internal error: Cannot run program "C:\Windows\System32\wsl.exe \usr\bin\ansible-vault" (in directory "C:\Users\xxx"): CreateProcess error=2, Le fichier spécifié est introuvable`

or

![image](https://user-images.githubusercontent.com/25756297/118824582-42dade80-b8ba-11eb-84e7-e66800860528.png)

Got the error `Error: Exited with code 127: /bin/bash: encrypt: command not found`

**Comment by timo-reymann** [comment]
Hi @jeromemartin,

first thank you for using my plugin.

I can not really test with WSL, because i currently have no setup for this.
So i can only give you suggestions, based on documentation (https://docs.microsoft.com/en-us/windows/wsl/reference#arguments-for-running-linux-commands), sorry about that.

What you can try is the following:

Choose ansible vault:
C:/Windows/System32/wsl.exe

Command line args:
-- /usr/bin/ansible-vault

The problem in the first place is that the ansible vault executable is the entry point for the execution and the arguments are simply splitted and passed to the executable. So i guess this leads to problems with the interpreter, so maybe adding the special --` argument works.

**Comment by timo-reymann** [comment]
Okay so i had to set up WSL for another project and you are right currently its simply not possible to use the ansible-vault command on wsl.

Because the userbase for wsl is very low for this plugin, this has not really a high priority and for the future i might implement sth like a _WSL Checkbox_
